apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  labels:
    app: "{{ .Release.Name }}-maria-db"
  name: "{{ .Release.Name }}-maria-db"
  namespace: default
spec:
  serviceName: "{{ .Release.Name }}-maria-db"
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-maria-db"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-maria-db"
    spec:
      containers:
        - image: {{ .Values.mariadb.image.repository }}:{{ .Values.mariadb.image.tag }}
          imagePullPolicy: {{ .Values.mariadb.image.pullPolicy }}
          name: "{{ .Release.Name }}-maria-db"
          resources: {}
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-maria-db"
                  key: rootPassword
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-maria-db"
                  key: database
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-maria-db"
                  key: user
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-maria-db"
                  key: password
          ports:
            - containerPort: {{ .Values.servicemariadb.port }}
              name: mysql
          volumeMounts:
            - name: {{ .Release.Name }}-{{ .Values.mariadb.volumeMounts.name }}
              mountPath: {{ .Values.mariadb.volumeMounts.mountPath}}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: {{ .Release.Name }}-{{ .Values.mariadb.volumes.name }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-{{ .Values.mariadb.volumes.nameClaim }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-{{ .Values.pvmariadb.name }}
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: {{ .Values.pvmariadb.persistentVolumeReclaimPolicy }}
  storageClassName: standard
  capacity:
    storage: {{ .Values.pvmariadb.size }}
  hostPath:
    path: /data/"{{ .Release.Name }}-maria-db"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ .Values.pvcmariadb.name }}
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvcmariadb.size }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.servicemariadb.name }}
spec:
  ports:
    - port: {{ .Values.servicemariadb.port }}
  selector:
    app: {{ .Release.Name }}-{{ .Values.servicemariadb.name }}