apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-mariadb-secret"
data:
  user: {{ .Values.mariadb.auth.user | b64enc | quote }}
  password: {{ .Values.mariadb.auth.password | b64enc | quote }}
  database: {{ .Values.mariadb.auth.database | b64enc | quote }}
  hostname: {{ .Release.Name | b64enc | quote }}
